### ISSUE TITLE
Play command doesn't work 

### ISSUE THREAD

**Issue by Mykeyy** [frogyushi/hazel#3]
![image](https://user-images.githubusercontent.com/92008679/182427122-52fc73ea-0d98-4767-a729-c1975064532d.png)
![image](https://user-images.githubusercontent.com/92008679/182436302-7325a692-993c-4788-ab96-ffd87480c554.png)

having an issue when you type play this happens I try everything it still doesn't work

**Comment by frogyushi** [comment]
thank u for the heads-up! this has been a known issue with hazel and ill update u asap on whenever i get the chance to fix it. for now <ahsw7>'s solution works - thank u btw :)
